language: node_js

node_js:
  - 0.11

env:
  matrix:
    - BROWSER='chrome_linux'    BUILD='default'
    - BROWSER='firefox_linux'   BUILD='default'
    - BROWSER='ie11'            BUILD='default'
    - BROWSER='ie7'             BUILD='default'
    - BROWSER='ie6'             BUILD='default'  
    
  global:
    - SAUCE_USERNAME=sergiosbox_core
    - SAUCE_ACCESS_KEY=e9cd398c-418d-47ae-9285-e5b7a5ed9f10

before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash

