language: node_js

node_js:
  - '4'

env:
  matrix:
    - BUILD='compat'     BROWSER='phantomjs'
    - BUILD='compat'     BROWSER='safari9'
    - BUILD='compat'     BROWSER='safari8'
    - BUILD='nocompat'   BROWSER='safari8'


    - BUILD='server'

  global:
    - SAUCE_USERNAME=sergiosbox_core
    - SAUCE_ACCESS_KEY=e9cd398c-418d-47ae-9285-e5b7a5ed9f10

matrix:
  include:
    - node_js: '0.12'
      env: BUILD='server'
    - node_js: '0.10'
      env: BUILD='server'

cache:
  directories:
    - node_modules

sudo: false
