language: node_js

node_js:
- 0.11

env:
  global:
    - SAUCE_USERNAME=sergiosbox_core
    - SAUCE_ACCESS_KEY=e9cd398c-418d-47ae-9285-e5b7a5ed9f10
    
before_script:
    - npm install grunt-cli -g
    - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  
script:
  #- grunt test --reporters dots --browsers SL_Chrome
  - grunt --verbose default:travis
