language: node_js

node_js:
  - "0.10"

env:
  matrix:
    - BROWSER='chrome_linux'
    - BROWSER='firefox_linux'
    - BROWSER='opera_win2000'
    - BROWSER='safari8'
    - BROWSER='safari7'
    - BROWSER='safari6'
    - BROWSER='ie11'
    - BROWSER='ie10'
    - BROWSER='ie9'
    - BROWSER='ie8'
    - BROWSER='ie7'
    - BROWSER='phantomjs'

  global:
    - SAUCE_USERNAME=sergiosbox_core
    - SAUCE_ACCESS_KEY=e9cd398c-418d-47ae-9285-e5b7a5ed9f10
    
before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash

sudo: false
